 version: 2.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: win/default     
    
     steps:
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "MusixmatchClientLib/MusixmatchClientLib.csproj" }}
      - restore_dependencies:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "MusixmatchClientLib/MusixmatchClientLib.csproj" }}
      - build:
          name: "Build project"
          command: dotnet build
