version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Installing project dependencies"
          command: dotnet restore
      - run:
          name: "Building the solution"
          command: dotnet publish -c Release -r win10-x64
      - store_artifacts:
          path: .\bin\Release\netstandard2.0\win10-x64\publish\MusixmatchClientLib.dll
